/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import DataBase.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JRadioButton;
import Controlador.*;
import Modelo.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author axel
 */
public class CRUD_ropa extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_ropa
     */
    ButtonGroup btnGr;
    ButtonGroup btnGr1;
    private Usuario user;
    private String imagenRopa;
    
    public CRUD_ropa(Usuario user) {
        this.user=user;
        initComponents();
        btnGr = new ButtonGroup();
        btnGr1 = new ButtonGroup();
        btnGr.add(rbmasculino);
        btnGr.add(rbfemenino);
        btnGr1.add(rbsuperior);
        btnGr1.add(rbinferior);
        btnGr1.add(rbcalzado);
        CargarTabla();
        txtID.setEditable(false);
        //CargarComboTallas();
        jLabel4.setVisible(false);
        cmbtalla.setVisible(false);
        jScrollPane3.setVisible(false);
        txtexistencias.setVisible(false);
        btbagregartalla.setVisible(false);
        imagenRopa = "imagenDefault.jpg";
        btnvolver.setVisible(false);
        jLabel11.setVisible(false);
        btnlimpiartallas.setVisible(false);
    }
    int claseSeleccionada =1;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabRopa = new javax.swing.JTabbedPane();
        Listado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaropa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbfiltro = new javax.swing.JComboBox<>();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnRestablecer = new javax.swing.JButton();
        txtVolver = new javax.swing.JLabel();
        Operaciones = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpreciocosto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtprecioventa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnseleccionartalla = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btbagregartalla = new javax.swing.JButton();
        btnlimpiartallas = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtexistencias = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbtalla = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbtipo1 = new javax.swing.JComboBox<>();
        txtmarca = new javax.swing.JTextField();
        btnAgregarImagen = new javax.swing.JButton();
        lblRopa = new javax.swing.JLabel();
        rbsuperior = new javax.swing.JRadioButton();
        rbinferior = new javax.swing.JRadioButton();
        rbcalzado = new javax.swing.JRadioButton();
        rbmasculino = new javax.swing.JRadioButton();
        rbfemenino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaropa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripcion", "P.Costo", "P.Venta", "Ganancia", "Genero", "Marca", "Clase", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaropa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaropaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaropa);

        jLabel1.setText("Listado de Ropa");

        jButton1.setText("Encontrar");

        jButton2.setText("Nuevo");

        jButton3.setText("Editar");

        jButton4.setText("Desactivar");

        jButton5.setText("Activar");

        jLabel3.setText("Registros");

        cmbfiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nombre", "Genero", "Marca", "Clase", "Tipo" }));

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnRestablecer.setText("Restablecer tabla");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        txtVolver.setText("< Volver al menu");
        txtVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListadoLayout = new javax.swing.GroupLayout(Listado);
        Listado.setLayout(ListadoLayout);
        ListadoLayout.setHorizontalGroup(
            ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ListadoLayout.createSequentialGroup()
                        .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ListadoLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(47, 47, 47)
                                .addComponent(jButton2)
                                .addGap(43, 43, 43)
                                .addComponent(btnRestablecer, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addGap(64, 64, 64)
                                .addComponent(jButton3))
                            .addGroup(ListadoLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel3))
                            .addGroup(ListadoLayout.createSequentialGroup()
                                .addComponent(cmbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtbuscar)))
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ListadoLayout.createSequentialGroup()
                .addComponent(txtVolver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ListadoLayout.setVerticalGroup(
            ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListadoLayout.createSequentialGroup()
                .addComponent(txtVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnRestablecer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        TabRopa.addTab("Listado", Listado);

        jLabel4.setText("Edicion de Ropa:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("ID");

        jLabel7.setText("Descripcion");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        jLabel8.setText("Clase de Prenda");

        jLabel9.setText("Genero:");

        jLabel10.setText("Precio Costo:");

        jLabel11.setText("Precio Venta:");

        jLabel12.setText("Marca:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talla", "Existencias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        btnseleccionartalla.setText("Seleccionar Tallas");
        btnseleccionartalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionartallaActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Agregar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btbagregartalla.setText("Agregar talla");
        btbagregartalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbagregartallaActionPerformed(evt);
            }
        });

        btnlimpiartallas.setText("Limpiar");
        btnlimpiartallas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiartallasActionPerformed(evt);
            }
        });

        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        jLabel13.setText("Existencias");

        jLabel14.setText("Talla:");

        cmbtalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clase" }));

        jLabel15.setText("Tipo de prenda:");

        cmbtipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clase de prenda primero" }));

        btnAgregarImagen.setText("Agregar imagen");
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });

        lblRopa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rbsuperior.setBackground(new java.awt.Color(255, 255, 255));
        rbsuperior.setText("Superior");
        rbsuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbsuperiorMouseClicked(evt);
            }
        });

        rbinferior.setBackground(new java.awt.Color(255, 255, 255));
        rbinferior.setText("Inferior");
        rbinferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbinferiorMouseClicked(evt);
            }
        });

        rbcalzado.setBackground(new java.awt.Color(255, 255, 255));
        rbcalzado.setText("Calzado");
        rbcalzado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbcalzadoMouseClicked(evt);
            }
        });

        rbmasculino.setBackground(new java.awt.Color(255, 255, 255));
        rbmasculino.setText("Masculino");

        rbfemenino.setBackground(new java.awt.Color(255, 255, 255));
        rbfemenino.setText("Femenino");

        javax.swing.GroupLayout OperacionesLayout = new javax.swing.GroupLayout(Operaciones);
        Operaciones.setLayout(OperacionesLayout);
        OperacionesLayout.setHorizontalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperacionesLayout.createSequentialGroup()
                                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OperacionesLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtpreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbsuperior)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbinferior)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbcalzado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(rbmasculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbfemenino))
                                    .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(OperacionesLayout.createSequentialGroup()
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2)))
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(btnseleccionartalla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbtalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperacionesLayout.createSequentialGroup()
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbtipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(OperacionesLayout.createSequentialGroup()
                                        .addComponent(btbagregartalla, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnlimpiartallas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnvolver)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRopa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(OperacionesLayout.createSequentialGroup()
                                .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarImagen)))
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
        OperacionesLayout.setVerticalGroup(
            OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rbsuperior)
                            .addComponent(rbinferior)
                            .addComponent(rbcalzado)))
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rbmasculino)
                            .addComponent(rbfemenino))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtpreciocosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtprecioventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnseleccionartalla)
                    .addComponent(jLabel13)
                    .addComponent(txtexistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cmbtalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperacionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbagregartalla)
                            .addComponent(btnlimpiartallas)
                            .addComponent(btnvolver))
                        .addGap(18, 18, 18)
                        .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cmbtipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(lblRopa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(OperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAgregarImagen))
                .addContainerGap())
        );

        TabRopa.addTab("Operaciones", Operaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabRopa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabRopa)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaropaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaropaMouseClicked
        //Este metodo es para que se le pueda hacer clic a la tabla
        try
        {
            int fila = tablaropa.getSelectedRow();
            int id = Integer.parseInt(tablaropa.getValueAt(fila, 0).toString());
            PreparedStatement ps, ps2;
            ResultSet rs, rs2;
            ResultSetMetaData rsm;
            Connection con = Conexion.getCon();
            Connection con2 = Conexion.getCon();
            String consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.genero, r.marca,r.imagen, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.idropa=? ";
            String consulta_talla = "SELECT t.nombre, rt.existencias FROM Tallas t INNER JOIN ropa_talla rt ON t.idtalla = rt.idtalla INNER JOIN ropa r ON rt.idropa = r.idropa WHERE r.idropa=?";
            ps=con.prepareStatement(consultaSQL);
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while(rs.next())
            {
                txtID.setText(String.valueOf(id));
                txtNombre.setText(rs.getString(2));
                txtDescripcion.setText(rs.getString(3));
                //pintarImagen(imagenRopa, "src/presentacion/img/categorias/"+rs.getString(8));
                txtpreciocosto.setText(rs.getString(4));
                txtprecioventa.setText(rs.getString(5));
                //cmbtalla.setSelectedItem(rs.getString("talla"));
                if(rs.getString(6).equals("Masculino"))
                {
                    rbmasculino.setSelected(true);
                }else if(rs.getString(6).equals("Femenino"))
                {
                    rbfemenino.setSelected(true);
                }
                //txtcantidad.setText(rs.getString("cantidad"));
                txtmarca.setText(rs.getString(7));
                if(rs.getString(8).equals("Superior"))
                {
                    rbsuperior.setSelected(true);
                    TraerTipos(1);
                    TraerTallas(1);
                }else
                {
                    if(rs.getString(8).equals("Inferior"))
                    {
                        rbinferior.setSelected(true);
                        TraerTipos(2);
                        TraerTallas(2);
                    }else if(rs.getString(8).equals("Calzado"))
                    {
                        rbcalzado.setSelected(true);
                        TraerTipos(3);
                        TraerTallas(3);
                    }
                }
                cmbtipo1.setSelectedItem(rs.getString(9));

                DefaultTableModel modelotabla = (DefaultTableModel) jTable1.getModel();
                modelotabla.setRowCount(0);
                ps2 = con2.prepareStatement(consulta_talla);
                ps2.setInt(1, id);
                rs2 = ps2.executeQuery();
                rsm = rs2.getMetaData();
                int columnas = rsm.getColumnCount();;
                while(rs2.next())
                {
                    Object[] fila2 = new Object[columnas];
                    for(int indice=0; indice<columnas; indice++)
                    {
                        fila2[indice] = rs2.getObject(indice+1);
                    }
                    modelotabla.addRow(fila2);
                }
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tablaropaMouseClicked

    private void btnseleccionartallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionartallaActionPerformed
        System.out.println(claseSeleccionada);
        MostrarOcultarComponentes(false);
    }//GEN-LAST:event_btnseleccionartallaActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        SQL_Ropa modSql = new SQL_Ropa();
        Ropa mod = new Ropa();
        String nombre = txtNombre.getText();
        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes de ingresar un nombre a la prenda");
        } else {
            mod.setNombre(nombre);
            String descripcion = txtDescripcion.getText();
            if (descripcion.equals("")) {
                JOptionPane.showMessageDialog(null, "Debes de ingresar una descripcion a la prenda");
            } else {
                mod.setDescripcion(descripcion);
                String imagen = imagenRopa;
                if (imagen.equals("imagenDefault.jpg")) {
                    JOptionPane.showMessageDialog(null, "Debes ingresar una imagen del producto");
                } else {
                    mod.setImagen(imagen);
                    if (txtpreciocosto.getText().equals("") && txtprecioventa.getText().equals("")) {
                        JOptionPane.showMessageDialog(null, "Debe ingresar valores en los precios");
                    } else {

                        boolean bandera = false;
                        try {
                            double precio_costo = Double.parseDouble(txtpreciocosto.getText());
                            double precio_venta = Double.parseDouble(txtprecioventa.getText());
                            if (precio_costo > 0 && precio_venta > 0) {
                                if (precio_venta > precio_costo) {
                                    mod.setPrecio_costo(precio_costo);
                                    mod.setPrecio_venta(precio_venta);
                                    mod.setGanancia(precio_venta - precio_costo);
                                    bandera = true;
                                } else {
                                    JOptionPane.showMessageDialog(null, "El precio de costo no debe ser mayor al de venta");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "Los precios deben ser mayores a cero");
                            }
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en el precio");
                        }
                        if (bandera) {
                            if (cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")) {
                                JOptionPane.showMessageDialog(null, "Debe seleccionar una talla");
                            } else {
                                String sexo;
                                if (rbmasculino.isSelected() == true) {
                                    sexo = "Masculino";
                                    mod.setGenero(sexo);
                                } else {
                                    if (rbfemenino.isSelected() == true) {
                                        sexo = "Femenino";
                                        mod.setGenero(sexo);
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Debe seleccionar un genero");
                                    }
                                }
                                try {
                                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                    if (model.getRowCount() > 0) {
                                        /*
                                     for (int i = 0; i<model.getRowCount(); i++) {
                                        final String col1 = (String) model.getValueAt(i, 0);
                                        final String col2 = (String) model.getValueAt(i, 1);
                                        System.out.println("Talla: " + col1 + " Existencia: " + col2);
                                    }
                                         */
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Debe Agregar las tallas");
                                    }
                                } catch (NumberFormatException e) {
                                    JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en las existencias");
                                }
                                String marca = txtmarca.getText();
                                if (marca.equals("")) {
                                    JOptionPane.showMessageDialog(null, "Debes de ingresar una marca");
                                } else {
                                    mod.setMarca(marca);
                                    int clase = -1;
                                    if (rbsuperior.isSelected() == true) {
                                        clase = 1;
                                    } else {
                                        if (rbinferior.isSelected() == true) {
                                            clase = 2;
                                        } else {
                                            if (rbcalzado.isSelected() == true) {
                                                clase = 3;
                                            }
                                        }
                                    }
                                    if (!cmbtipo1.getSelectedItem().toString().equals("Seleccione una clase de prenda primero")) {
                                        mod.setIdtipoprenda(traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase));
                                    } else {
                                        JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de ropa");
                                    }
                                    if (modSql.Agregar(mod)) {
                                        //consulta para traer el ultimo id deROPA REGISTRADO
                                        //SELECT MAX(idropa) AS 'idropa' FROM ropa
                                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                        if (model.getRowCount() > 0) {
                                            SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                                            for (int i = 0; i < model.getRowCount(); i++) {

                                                Ropa_Tallas rt = new Ropa_Tallas();
                                                rt.setIdropa(traerUltimoIDRopa());
                                                rt.setIdtalla(traerIDTalla(model.getValueAt(i, 0).toString(), clase));
                                                rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                                sqlropatallas.Agregar(rt);
                                            }
                                        }
                                        //una vez que guardo la ropa guardara las tallas

                                        JOptionPane.showMessageDialog(this, "Registro guardado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                                        Limpiar();
                                        CargarTabla();
                                    } else {
                                        JOptionPane.showMessageDialog(this, "Error al guardar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = 0;
        boolean ban = false;
        try {
            id = Integer.parseInt(txtID.getText());
            ban = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla para obtener un id");
        }
        SQL_Ropa modSql = new SQL_Ropa();
        Ropa mod = new Ropa();
        String nombre = txtNombre.getText();
        if (ban) {
            if (nombre.equals("")) {
                JOptionPane.showMessageDialog(null, "Debes de ingresar un nombre a la prenda");
            } else {
                mod.setNombre(nombre);
                String descripcion = txtDescripcion.getText();
                if (descripcion.equals("")) {
                    JOptionPane.showMessageDialog(null, "Debes de ingresar una descripcion a la prenda");
                } else {
                    mod.setDescripcion(descripcion);
                    String imagen = imagenRopa;
                    if (imagen.equals("imagenDefault.jpg")) {
                        JOptionPane.showMessageDialog(null, "Debes ingresar una imagen del producto");
                    } else {
                        mod.setImagen(imagen);
                        if (txtpreciocosto.getText().equals("") && txtprecioventa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Debe ingresar valores en los precios");
                        } else {
                            boolean bandera = false;
                            try {
                                double precio_costo = Double.parseDouble(txtpreciocosto.getText());
                                double precio_venta = Double.parseDouble(txtprecioventa.getText());
                                if (precio_costo > 0 && precio_venta > 0) {
                                    if (precio_venta > precio_costo) {
                                        mod.setPrecio_costo(precio_costo);
                                        mod.setPrecio_venta(precio_venta);
                                        mod.setGanancia(precio_venta - precio_costo);
                                        bandera = true;
                                    } else {
                                        JOptionPane.showMessageDialog(null, "El precio de costo no debe ser mayor al de venta");
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(null, "Los precios deben ser mayores a cero");
                                }
                            } catch (NumberFormatException e) {
                                JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en el precio");
                            }
                            if (bandera) {
                                if (cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")) {
                                    JOptionPane.showMessageDialog(null, "Debe seleccionar una talla");
                                } else {
                                    String sexo;
                                    if (rbmasculino.isSelected() == true) {
                                        sexo = "Masculino";
                                        mod.setGenero(sexo);
                                    } else {
                                        if (rbfemenino.isSelected() == true) {
                                            sexo = "Femenino";
                                            mod.setGenero(sexo);
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Debe seleccionar un genero");
                                        }
                                    }
                                    try {
                                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                        if (model.getRowCount() > 0) {
                                            /*
                                        for (int i = 0; i<model.getRowCount(); i++) {
                                            final String col1 = (String) model.getValueAt(i, 0);
                                            final String col2 = (String) model.getValueAt(i, 1);
                                            System.out.println("Talla: " + col1 + " Existencia: " + col2);
                                        }
                                             */
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Debe Agregar las tallas");
                                        }
                                    } catch (NumberFormatException e) {
                                        JOptionPane.showMessageDialog(null, "Debe ingresar un valor numerico en las existencias");
                                    }
                                    String marca = txtmarca.getText();
                                    if (marca.equals("")) {
                                        JOptionPane.showMessageDialog(null, "Debes de ingresar una marca");
                                    } else {
                                        mod.setMarca(marca);
                                        int clase = -1;
                                        if (rbsuperior.isSelected() == true) {
                                            clase = 1;
                                        } else {
                                            if (rbinferior.isSelected() == true) {
                                                clase = 2;
                                            } else {
                                                if (rbcalzado.isSelected() == true) {
                                                    clase = 3;
                                                }
                                            }
                                        }
                                        if (!cmbtipo1.getSelectedItem().toString().equals("Seleccione una clase de prenda primero")) {
                                            mod.setIdtipoprenda(traerIDTipoPrenda(cmbtipo1.getSelectedItem().toString(), clase));
                                        } else {
                                            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo de ropa");
                                        }
                                        mod.setIdropa(id);
                                        if (modSql.Modificar(mod)) {
                                            //consulta para traer el ultimo id deROPA REGISTRADO
                                            //SELECT MAX(idropa) AS 'idropa' FROM ropa
                                            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                                            if (model.getRowCount() > 0) {
                                                Ropa_Tallas rt = new Ropa_Tallas();
                                                SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                                                sqlropatallas.Eliminar(id);
                                                for (int i = 0; i < model.getRowCount(); i++) {

                                                    rt.setIdropa(id);
                                                    rt.setIdtalla(traerIDTalla(model.getValueAt(i, 0).toString(), clase));
                                                    rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                                                    sqlropatallas.Agregar(rt);
                                                }
                                            }
                                            //una vez que guardo la ropa guardara las tallas

                                            JOptionPane.showMessageDialog(this, "Registro guardado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                                            Limpiar();
                                            CargarTabla();
                                        } else {
                                            JOptionPane.showMessageDialog(this, "Error al guardar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id = 0;
        try
        {
            id = Integer.parseInt(txtID.getText());
        }catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla para obtener un id");
        }
        if(!txtID.getText().equals(""))
        {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            if(model.getRowCount()>0){/*
                for (int i = 0; i<model.getRowCount(); i++) {
                    final String col1 = (String) model.getValueAt(i, 0);
                    final String col2 = (String) model.getValueAt(i, 1);
                    System.out.println("Talla: " + col1 + " Existencia: " + col2);
                }*/
                //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                if(model.getRowCount()>0){
                    SQL_Ropa_Tallas sqlropatallas = new SQL_Ropa_Tallas();
                    for (int i = 0; i<model.getRowCount(); i++)
                    {
                        Ropa_Tallas rt =new Ropa_Tallas();
                        rt.setIdropa(id);
                        rt.setIdtalla(traerIDTalla((String) model.getValueAt(i, 0), 0));
                        rt.setExistencias(Integer.parseInt(model.getValueAt(i, 1).toString()));
                        sqlropatallas.Eliminar(id);
                    }
                }
                try
                {
                    Connection con = Conexion.getCon();
                    PreparedStatement ps = con.prepareStatement("DELETE FROM ropa WHERE idropa=?");
                    ps.setInt(1, Integer.parseInt(txtID.getText()));
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Registro eliminado", "Registro", JOptionPane.INFORMATION_MESSAGE);
                    Limpiar();
                    CargarTabla();
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(this, "Error al eliminar el registro", "Registro", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btbagregartallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbagregartallaActionPerformed
        if(!(cmbtalla.getSelectedItem().toString().equals("Seleccione una clase")))
        {
            int existencias = Integer.parseInt(txtexistencias.getText());
            if(existencias > 0)
            {
                try
                {
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    int columnas = model.getRowCount();
                    boolean existe =false;
                    for (int i = 0; i<columnas; i++) {
                        if(model.getValueAt(i, 0).toString().equalsIgnoreCase(cmbtalla.getSelectedItem().toString())){
                            existe = true;
                            break;
                        }
                    }
                    if (!existe) {
                        Object[] row = { cmbtalla.getSelectedItem(), existencias};
                        model.addRow(row);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ya tienes esta talla registradas");
                    }

                }catch(NumberFormatException e)
                {
                    JOptionPane.showMessageDialog(null, "Debes ingresar un valor numerico en las existencias");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No puedes agregar existencias negativas");
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una talla");
        }
    }//GEN-LAST:event_btbagregartallaActionPerformed

    private void btnlimpiartallasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiartallasActionPerformed
        LimpiarTablaTallas();
    }//GEN-LAST:event_btnlimpiartallasActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        MostrarOcultarComponentes(true);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        /*if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER)
        {
            btnbuscarActionPerformed(java.awt.event.ActionEvent evt);
            se crearia un nuevo metodo con lo del boton de buscar
        }*/
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        DefaultTableModel modelotabla = (DefaultTableModel) tablaropa.getModel();
        modelotabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        String busqueda = txtbuscar.getText();
        if(busqueda.trim().equals(""))
        {
            CargarTabla();
        }
        else
        {
            int columnas;
            int[] anchos = {30,100,150,40,30,60,40,70,80,124};
            for(int i = 0; i<tablaropa.getColumnCount(); i++)
            {
                tablaropa.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }
            try
            {
                Connection con = Conexion.getCon();
                String consultaSQL = "";
                String filtro = cmbfiltro.getSelectedItem().toString();
                if(filtro.equals("Id"))
                {
                    consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.idropa = '"+busqueda+"' ";
                }else
                {
                    if(filtro.equals("Nombre"))
                    {
                        consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.nombre like '%"+busqueda+"%' ";
                    }else
                    {
                        if(filtro.equals("Genero"))
                        {
                            consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.genero like '%"+busqueda+"%' ";
                        }
                        else
                        {
                            if(filtro.equals("Marca"))
                            {
                                consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.marca like '%"+busqueda+"%' ";
                            }
                            else
                            {
                                if(filtro.equals("Clase"))
                                {
                                    consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE cp.nombre like '%"+busqueda+"%' ";
                                }
                                else
                                {
                                    if(filtro.equals("Tipo"))
                                    {
                                        consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE tp.nombre like '%"+busqueda+"%' ";
                                    }
                                }
                            }
                        }
                    }
                }
                ps = con.prepareStatement(consultaSQL);
                rs = ps.executeQuery();
                rsmd = rs.getMetaData();
                columnas = rsmd.getColumnCount();
                while(rs.next())
                {
                    Object[] fila = new Object[columnas];
                    for(int indice=0; indice<columnas; indice++)
                    {
                        fila[indice] = rs.getObject(indice+1);
                    }
                    modelotabla.addRow(fila);
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        DefaultTableModel modelotabla = (DefaultTableModel) tablaropa.getModel();
        modelotabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        String busqueda = txtbuscar.getText();
        if(busqueda.trim().equals(""))
        {
            //CargarTabla();
            JOptionPane.showMessageDialog(null, "Debes ingresar un valor al campo de busqueda dependiendo del filtro seleccionado");
        }
        int columnas;
        //724 tamano tabla de forma horizontal
        int[] anchos = {30,100,150,40,30,60,40,70,80,124};
        for(int i = 0; i<tablaropa.getColumnCount(); i++)
        {
            tablaropa.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try
        {
            Connection con = Conexion.getCon();
            String consultaSQL = "";
            String filtro = cmbfiltro.getSelectedItem().toString();
            if(filtro.equals("Id"))
            {
                consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.idropa = '"+busqueda+"' ";
            }else
            {
                if(filtro.equals("Nombre"))
                {
                    consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.nombre like '%"+busqueda+"%' ";
                }else
                {
                    if(filtro.equals("Genero"))
                    {
                        consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE r.genero like '%"+busqueda+"%' ";
                    }
                    else
                    {
                        if(filtro.equals("Marca"))
                        {
                            consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda  WHERE r.marca like '%"+busqueda+"%' ";
                        }
                        else
                        {
                            if(filtro.equals("Clase"))
                            {
                                consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE cp.nombre like '%"+busqueda+"%' ";
                            }
                            else
                            {
                                if(filtro.equals("Tipo"))
                                {
                                    consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda WHERE tp.nombre like '%"+busqueda+"%' ";
                                }
                            }
                        }
                    }
                }
            }
            ps = con.prepareStatement(consultaSQL);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next())
            {
                Object[] fila = new Object[columnas];
                for(int indice=0; indice<columnas; indice++)
                {
                    fila[indice] = rs.getObject(indice+1);
                }
                modelotabla.addRow(fila);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        CargarTabla();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void rbsuperiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbsuperiorMouseClicked
        TraerTallas(1);
        TraerTipos(1);
        claseSeleccionada=1;
        LimpiarTablaTallas();
    }//GEN-LAST:event_rbsuperiorMouseClicked

    private void rbinferiorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbinferiorMouseClicked
        TraerTallas(2);
        TraerTipos(2);
        claseSeleccionada=2;
        LimpiarTablaTallas();
    }//GEN-LAST:event_rbinferiorMouseClicked

    private void rbcalzadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbcalzadoMouseClicked
        TraerTallas(3);
        TraerTipos(3);
        claseSeleccionada=3;
        LimpiarTablaTallas();
    }//GEN-LAST:event_rbcalzadoMouseClicked

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        String ruta;
        //crear un obj que permita seleccionar un archvio
        JFileChooser jf = new JFileChooser();
        //establecer un filtro para seleccion de imagenes
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Gif,JPG,PNG", "gif","jpg","png");
        // establecer el filtro al objeto jf
        jf.setFileFilter(filtro);
        // abrir el cuadro de dialogo
        int resp = jf.showOpenDialog(this);
        // validar la respuesta
        if(resp == JFileChooser.APPROVE_OPTION){
            // obtener la ruta del archivo seleccionado
            ruta = jf.getSelectedFile().getPath();
            // obtener el nombre del archivo seleccionado
            imagenRopa = jf.getSelectedFile().getName();
            // pintar la imagen que selecciono el usuario
            pintarImagen(lblRopa,ruta);
        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void txtVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVolverMouseClicked
        dispose();
        MenuPrincipal.frmCRopa = null;
    }//GEN-LAST:event_txtVolverMouseClicked

    public void pintarImagen(JLabel lbl, String ruta){
         ImageIcon imagen = new ImageIcon(ruta);
         Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH));
         lbl.setIcon(icono);
         repaint();   
     }
    private void TraerTallas(int idClase){
        try
        {
            Connection con = Conexion.getCon();
            String consultaSQL = "select idtalla,nombre from Tallas where idclasePrenda=?";
            PreparedStatement ps;
            ResultSet rs;
            ps = con.prepareStatement(consultaSQL);
            ps.setInt(1, idClase);
            rs = ps.executeQuery();
            cmbtalla.removeAllItems();
            while(rs.next())
            {
               cmbtalla.addItem(rs.getString(2));
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void TraerTipos(int idClase)
    {
        try
        {
            Connection con = Conexion.getCon();
            String consultaSQL = "select idTipoPrenda,nombre from TipoPrenda where idclasePrenda=?";
            PreparedStatement ps;
            ResultSet rs;
            ps = con.prepareStatement(consultaSQL);
            ps.setInt(1, idClase);
            rs = ps.executeQuery();
            cmbtipo1.removeAllItems();
            while(rs.next())
            {
               cmbtipo1.addItem(rs.getString(2));
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void MostrarOcultarComponentes(boolean accion){
        jLabel5.setVisible(accion);
        rbmasculino.setVisible(accion);
        rbfemenino.setVisible(accion);
        jLabel7.setVisible(accion);
        jLabel9.setVisible(accion);
        cmbtipo1.setVisible(accion);
        txtmarca.setVisible(accion);
        btnAgregarImagen.setVisible(accion);
        btnEliminar.setVisible(accion);
        btnLimpiar.setVisible(accion);
        btnModificar.setVisible(accion);
        btnseleccionartalla.setVisible(accion);
        jLabel3.setVisible(accion);
        txtpreciocosto.setVisible(accion);
        jLabel6.setVisible(accion);
        txtprecioventa.setVisible(accion);
        
        btbagregartalla.setVisible(!accion);
        txtexistencias.setVisible(!accion);
        jLabel4.setVisible(!accion);
        cmbtalla.setVisible(!accion);
        jScrollPane3.setVisible(!accion);
        btnvolver.setVisible(!accion);
        jLabel11.setVisible(!accion);
        btnlimpiartallas.setVisible(!accion);
    }
     private void CargarTabla()
    {
        DefaultTableModel modelotabla = (DefaultTableModel) tablaropa.getModel();
        modelotabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        java.sql.ResultSetMetaData rsmd;
        int columnas;
        //724 tamano tabla de forma horizontal
        int[] anchos = {40,100,150,50,50,50,60,70,80,110};
        for(int i = 0; i<tablaropa.getColumnCount(); i++)
        {
            tablaropa.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        try
        {
            Connection con = Conexion.getCon();
            //String consultaSQL = "SELECT idropa, nombre, descripcion, precio, genero, marca FROM ropa";
            String consultaSQL = "SELECT DISTINCT r.idropa, r.nombre, r.descripcion, r.precio_costo, r.precio_venta, r.ganancia, r.genero, r.marca, cp.nombre, tp.nombre FROM ropa r INNER JOIN ropa_talla rp ON r.idropa = rp.idropa INNER JOIN Tallas t ON rp.idtalla=t.idtalla INNER JOIN ClasePrenda cp ON t.idclasePrenda=cp.idClasePrenda INNER JOIN TipoPrenda tp ON r.idtipoprenda = tp.idTipoPrenda ";
            ps = con.prepareStatement(consultaSQL);
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            Object[] fila = new Object[columnas];
            while(rs.next())
            {
                fila[0] = rs.getInt(1);
                fila[1] = rs.getString(2);
                fila[2] = rs.getString(3);
                fila[3] = rs.getDouble(4);
                fila[4] = rs.getDouble(5);
                fila[5] = rs.getDouble(6);
                fila[6] = rs.getString(7);
                fila[7] = rs.getString(8);
                fila[8] = rs.getString(9);
                fila[9] = rs.getString(10);
                modelotabla.addRow(fila);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    private void Limpiar()
    {
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtpreciocosto.setText("");
        cmbtalla.setSelectedItem("Seleccione");
        txtmarca.setText("");
        btnGr.clearSelection();
        btnGr1.clearSelection();
        cmbtipo1.setVisible(true);
        txtID.setText("");
        cmbtalla.removeAllItems();
        cmbtalla.addItem("Seleccione una clase");
        cmbtalla.setSelectedItem("Seleccione una clase");
        cmbtipo1.addItem("Seleccione una clase de prenda primero");
        cmbtipo1.setSelectedItem("Seleccione una clase de prenda primero");
        txtexistencias.setText("");
        txtprecioventa.setText("");
        LimpiarTablaTallas();
    }
    private void LimpiarTablaTallas()
    {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) 
        {          
            tb.removeRow(tb.getRowCount()-1);
        }
        txtexistencias.setText("");
    }
    private int traerIDTipoPrenda(String nombre, int clase) {
        PreparedStatement ps = null;
        Connection con = Conexion.getCon();
        ResultSet rs;
        String consultaSQL = "Select idTipoPrenda from TipoPrenda where nombre=? and idclaseprenda=? ;";
        try {
            ps = con.prepareStatement(consultaSQL);
            ps.setString(1, nombre);
            ps.setInt(2, clase);
            rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt(1);
            }
            return -1;
        } catch (SQLException ex) {
            Logger.getLogger(SQL_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }

    private int traerIDTalla(String nombre, int clase) {
        PreparedStatement ps = null;
        Connection con = Conexion.getCon();
        ResultSet rs;
        String consultaSQL = "Select idtalla from Tallas where nombre=? and idclasePrenda=? ;";
        try {
            ps = con.prepareStatement(consultaSQL);
            ps.setString(1, nombre);
            ps.setInt(2, clase);
            rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt(1);
            }
            return -1;
        } catch (SQLException ex) {
            Logger.getLogger(SQL_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }

    private int traerUltimoIDRopa() {
        PreparedStatement ps = null;
        Connection con = Conexion.getCon();
        ResultSet rs;
        String consultaSQL = "Select MAX(idropa) from ropa;";
        try {
            ps = con.prepareStatement(consultaSQL);
            rs = ps.executeQuery();
            if (rs.next()) {
                return rs.getInt(1);
            }
            return -1;
        } catch (SQLException ex) {
            Logger.getLogger(SQL_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            return -1;
        }
    }
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_ropa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_ropa(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Listado;
    private javax.swing.JPanel Operaciones;
    private javax.swing.JTabbedPane TabRopa;
    private javax.swing.JButton btbagregartalla;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnlimpiartallas;
    private javax.swing.JButton btnseleccionartalla;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cmbfiltro;
    private javax.swing.JComboBox<String> cmbtalla;
    private javax.swing.JComboBox<String> cmbtipo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblRopa;
    private javax.swing.JRadioButton rbcalzado;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbinferior;
    private javax.swing.JRadioButton rbmasculino;
    private javax.swing.JRadioButton rbsuperior;
    private javax.swing.JTable tablaropa;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel txtVolver;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtexistencias;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtpreciocosto;
    private javax.swing.JTextField txtprecioventa;
    // End of variables declaration//GEN-END:variables
}
